// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmrmaelbgjxrxppzeabh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indtcm1hZWxiZ2p4cnhwcHplYWJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTEyNDYsImV4cCI6MjA2Mjc4NzI0Nn0.ET-jtmGvibCCx7TZJHLYlk2x_cneVYYTcP50FTROIsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);